{% set name = "monet_analysis" %}
{% set version = "0.1" %}

package:
  name: monet_anaylsis
  version: {{ version }}

#fix this once we have a tag
#source:
  #git_url: https://github.com/noaa-csl/MONET-analysis.git
  #git_tag: develop
  #url: https://github.com/noaa-oar-arl/MONET/archive/v2.1.5.tar.gz
  #sha256: 9329c5103c8dbb51d5146824d608a7be9d7250c7f299ca9ccc1562ea188df051
  #url: https://github.com/noaa-oar-arl/MONET/archive/v2.1.3-dev.2.tar.gz
  # sha256: 7027a0478cab0f877ebc7e412a0249d0578c0944fab4da6f341175995b957931

build:
  number: 0
  #noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - python >=3.6
  host:
    - python
    - pip
  run:
    - git
    - python
    - monet
    - monetio

about:
  home: https://github.com/noaa-csl/MONET-analysis.git
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - for meteorology and AQ
  doc_url: https://monet-anaylsis.readthedocs.io

#extra:
#  recipe-maintainers:
#    # GitHub IDs for maintainers of the recipe.
#    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
#    - bbakernoaa
